AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

require:
  - rubocop-minitest
  - rubocop-rake

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Style/EmptyElse:
  EnforcedStyle: empty
